# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQubeConnection'
    scannerMode: 'Other'
    organization: 'romanshchukintest'
    extraProperties: |
      sonar.projectKey=RomanShchukinTest_3
      sonar.projectName=RomanShchukinTest_3
- task: Maven@4.210.0
  inputs:
    mavenPomFile: 'DeepSpace/pom.xml'
    goals: 'clean verify -X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: JaCoCo
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
    codeCoverageClassFilter: '+com.microsoft.tfs.demo.Image'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
