# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQubeConnection'
    scannerMode: 'Other'
    organization: 'romanshchukintest'
    extraProperties: |
      sonar.projectKey=RomanShchukinTest_3
      sonar.projectName=RomanShchukinTest_3
- task: Maven@3.209.0
  inputs:
    mavenPomFile: 'DeepSpace/pom.xml'
    options: '-Dmaven.wagon.http.pool=false'
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: JaCoCo
    codeCoverageFailIfEmpty: true
    jdkVersionOption: 1.8
    mavenAuthenticateFeed: false
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true
#    codeCoverageClassFilter: '+com.microsoft.tfs.demo.Image'
    isJacocoCoverageReportXML: true
    sonarQubeRunAnalysis: true
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
